import type { DetailedLoan } from "./types";

export const detailedLoans: DetailedLoan[] = [
  {
    id: "1",
    bank: "National Bank of Egypt",
    type: "Home Loan",
    code: "LN-44821",
    branch: "Cairo – Maadi Branch",
    status: "Active",
    totalAmount: 450000,
    remaining: 382500,
    monthly: 5200,
    interestRate: "9.5%",
    duration: "15 Years",
    loanOfficer: "Eng. Mohamed Saleh",
    paidAmount: 67500,
    percentagePaid: 15,
    startDate: "Jan 2024",
    endDate: "Jan 2039",
  },
  {
    id: "2",
    bank: "Commercial International Bank",
    type: "Car Loan",
    code: "LN-44756",
    branch: "Giza – Dokki Branch",
    status: "Active",
    totalAmount: 280000,
    remaining: 196000,
    monthly: 4100,
    interestRate: "11.2%",
    duration: "7 Years",
    loanOfficer: "Ms. Sara Abdel Fattah",
    paidAmount: 84000,
    percentagePaid: 30,
    startDate: "Mar 2023",
    endDate: "Mar 2030",
  },
  {
    id: "3",
    bank: "Banque Misr",
    type: "Personal Loan",
    code: "LN-44690",
    branch: "Heliopolis Branch",
    status: "Active",
    totalAmount: 50000,
    remaining: 12500,
    monthly: 1100,
    interestRate: "14.0%",
    duration: "4 Years",
    loanOfficer: "Mr. Ahmed Kamal",
    paidAmount: 37500,
    percentagePaid: 75,
    startDate: "Jun 2022",
    endDate: "Jun 2026",
  },
  {
    id: "4",
    bank: "QNB Alahli",
    type: "Education Loan",
    code: "LN-44512",
    branch: "Nasr City Branch",
    status: "Completed",
    totalAmount: 95000,
    remaining: 0,
    monthly: null,
    interestRate: "7.5%",
    duration: "5 Years",
    loanOfficer: "Ms. Dina Hossam",
    paidAmount: 95000,
    percentagePaid: 100,
    startDate: "Sep 2020",
    endDate: "Sep 2025",
  },
];
